package club.banyuan.reservation.model;

//import com.alibaba.fastjson.annotation.JSONField;

import java.io.Serializable;
import java.util.Date;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.seat_id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_at
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
//    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.duration_at
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
//    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date durationAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.duration
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    private Byte duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actived
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    private Boolean actived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.seat_id
     *
     * @return the value of orders.seat_id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.seat_id
     *
     * @param seatId the value for orders.seat_id
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_at
     *
     * @return the value of orders.created_at
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_at
     *
     * @param createdAt the value for orders.created_at
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.duration_at
     *
     * @return the value of orders.duration_at
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public Date getDurationAt() {
        return durationAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.duration_at
     *
     * @param durationAt the value for orders.duration_at
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public void setDurationAt(Date durationAt) {
        this.durationAt = durationAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.duration
     *
     * @return the value of orders.duration
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public Byte getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.duration
     *
     * @param duration the value for orders.duration
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public void setDuration(Byte duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actived
     *
     * @return the value of orders.actived
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public Boolean getActived() {
        return actived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actived
     *
     * @param actived the value for orders.actived
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    public void setActived(Boolean actived) {
        this.actived = actived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jun 23 11:13:40 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", seatId=").append(seatId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", durationAt=").append(durationAt);
        sb.append(", duration=").append(duration);
        sb.append(", actived=").append(actived);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}